; Listing generated by Microsoft (R) Optimizing Compiler Version 19.33.31630.0 

include listing.inc

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

CONST	SEGMENT
$SG33093 DB	'1-2-0', 00H
?_Fake_alloc@std@@3U_Fake_allocator@1@B	ORG $+1		; std::_Fake_alloc
CONST	ENDS
PUBLIC	__local_stdio_printf_options
PUBLIC	_vfprintf_l
PUBLIC	printf
PUBLIC	?is_valid@Date@@AEAA_NHHH@Z			; Date::is_valid
PUBLIC	??0Date@@QEAA@PEAD@Z				; Date::Date
PUBLIC	?show@Date@@QEAA_NXZ				; Date::show
PUBLIC	main
PUBLIC	?_OptionsStorage@?1??__local_stdio_printf_options@@9@4_KA ; `__local_stdio_printf_options'::`2'::_OptionsStorage
PUBLIC	??_C@_0BL@LAGMJGHF@Error?5in?5allocating?5memory@ ; `string'
PUBLIC	??_C@_01JOAMLHOP@?9@				; `string'
PUBLIC	??_C@_0BB@PHMEIIIO@Invalid?5Date?4?4?4?$CB@	; `string'
PUBLIC	??_C@_0BB@BPDBBPKA@Date?5?3?5?$CFd?9?$CFd?9?$CFd?6@ ; `string'
EXTRN	free:PROC
EXTRN	malloc:PROC
EXTRN	exit:PROC
EXTRN	atoi:PROC
EXTRN	__acrt_iob_func:PROC
EXTRN	puts:PROC
EXTRN	__stdio_common_vfprintf:PROC
EXTRN	strlen:PROC
EXTRN	strncpy:PROC
EXTRN	strtok:PROC
;	COMDAT ?_OptionsStorage@?1??__local_stdio_printf_options@@9@4_KA
_BSS	SEGMENT
?_OptionsStorage@?1??__local_stdio_printf_options@@9@4_KA DQ 01H DUP (?) ; `__local_stdio_printf_options'::`2'::_OptionsStorage
_BSS	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$_vfprintf_l DD imagerel $LN3
	DD	imagerel $LN3+67
	DD	imagerel $unwind$_vfprintf_l
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$printf DD imagerel $LN3
	DD	imagerel $LN3+87
	DD	imagerel $unwind$printf
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$??0Date@@QEAA@PEAD@Z DD imagerel $LN4
	DD	imagerel $LN4+261
	DD	imagerel $unwind$??0Date@@QEAA@PEAD@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?show@Date@@QEAA_NXZ DD imagerel $LN4
	DD	imagerel $LN4+111
	DD	imagerel $unwind$?show@Date@@QEAA_NXZ
pdata	ENDS
pdata	SEGMENT
$pdata$main DD	imagerel $LN3
	DD	imagerel $LN3+38
	DD	imagerel $unwind$main
pdata	ENDS
;	COMDAT ??_C@_0BB@BPDBBPKA@Date?5?3?5?$CFd?9?$CFd?9?$CFd?6@
CONST	SEGMENT
??_C@_0BB@BPDBBPKA@Date?5?3?5?$CFd?9?$CFd?9?$CFd?6@ DB 'Date : %d-%d-%d', 0aH
	DB	00H						; `string'
CONST	ENDS
;	COMDAT ??_C@_0BB@PHMEIIIO@Invalid?5Date?4?4?4?$CB@
CONST	SEGMENT
??_C@_0BB@PHMEIIIO@Invalid?5Date?4?4?4?$CB@ DB 'Invalid Date...!', 00H ; `string'
CONST	ENDS
;	COMDAT ??_C@_01JOAMLHOP@?9@
CONST	SEGMENT
??_C@_01JOAMLHOP@?9@ DB '-', 00H			; `string'
CONST	ENDS
;	COMDAT ??_C@_0BL@LAGMJGHF@Error?5in?5allocating?5memory@
CONST	SEGMENT
??_C@_0BL@LAGMJGHF@Error?5in?5allocating?5memory@ DB 'Error in allocating'
	DB	' memory', 00H				; `string'
CONST	ENDS
xdata	SEGMENT
$unwind$main DD	010401H
	DD	06204H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?show@Date@@QEAA_NXZ DD 010901H
	DD	04209H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$??0Date@@QEAA@PEAD@Z DD 010e01H
	DD	0a20eH
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$printf DD 011801H
	DD	06218H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$_vfprintf_l DD 011801H
	DD	06218H
xdata	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
d1$ = 32
main	PROC
; File C:\CPA_CPP\CLASS\This_Pointer\self.cpp
; Line 71
$LN3:
	sub	rsp, 56					; 00000038H
; Line 72
	lea	rdx, OFFSET FLAT:$SG33093
	lea	rcx, QWORD PTR d1$[rsp]
	call	??0Date@@QEAA@PEAD@Z			; Date::Date
; Line 73
	lea	rcx, QWORD PTR d1$[rsp]
	call	?show@Date@@QEAA_NXZ			; Date::show
; Line 75
	xor	eax, eax
; Line 76
	add	rsp, 56					; 00000038H
	ret	0
main	ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ?show@Date@@QEAA_NXZ
_TEXT	SEGMENT
this$ = 48
?show@Date@@QEAA_NXZ PROC				; Date::show, COMDAT
; File C:\CPA_CPP\CLASS\This_Pointer\self.cpp
; Line 54
$LN4:
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 40					; 00000028H
; Line 55
	mov	rax, QWORD PTR this$[rsp]
	mov	r9d, DWORD PTR [rax+8]
	mov	rax, QWORD PTR this$[rsp]
	mov	r8d, DWORD PTR [rax+4]
	mov	rax, QWORD PTR this$[rsp]
	mov	edx, DWORD PTR [rax]
	mov	rcx, QWORD PTR this$[rsp]
	call	?is_valid@Date@@AEAA_NHHH@Z		; Date::is_valid
	movzx	eax, al
	test	eax, eax
	jne	SHORT $LN2@show
; Line 57
	lea	rcx, OFFSET FLAT:??_C@_0BB@PHMEIIIO@Invalid?5Date?4?4?4?$CB@
	call	printf
; Line 58
	xor	al, al
	jmp	SHORT $LN1@show
$LN2@show:
; Line 61
	mov	rax, QWORD PTR this$[rsp]
	mov	r9d, DWORD PTR [rax+8]
	mov	rax, QWORD PTR this$[rsp]
	mov	r8d, DWORD PTR [rax+4]
	mov	rax, QWORD PTR this$[rsp]
	mov	edx, DWORD PTR [rax]
	lea	rcx, OFFSET FLAT:??_C@_0BB@BPDBBPKA@Date?5?3?5?$CFd?9?$CFd?9?$CFd?6@
	call	printf
; Line 62
	mov	al, 1
$LN1@show:
; Line 63
	add	rsp, 40					; 00000028H
	ret	0
?show@Date@@QEAA_NXZ ENDP				; Date::show
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ??0Date@@QEAA@PEAD@Z
_TEXT	SEGMENT
cc_strDate$ = 32
L$ = 40
str_day$ = 48
str_month$ = 56
str_year$ = 64
this$ = 96
strDate$ = 104
??0Date@@QEAA@PEAD@Z PROC				; Date::Date, COMDAT
; File C:\CPA_CPP\CLASS\This_Pointer\self.cpp
; Line 29
$LN4:
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 88					; 00000058H
; Line 31
	mov	rcx, QWORD PTR strDate$[rsp]
	call	strlen
	mov	QWORD PTR L$[rsp], rax
; Line 32
	mov	rax, QWORD PTR L$[rsp]
	inc	rax
	mov	rcx, rax
	call	malloc
	mov	QWORD PTR cc_strDate$[rsp], rax
; Line 33
	cmp	QWORD PTR cc_strDate$[rsp], 0
	jne	SHORT $LN2@Date
; Line 35
	lea	rcx, OFFSET FLAT:??_C@_0BL@LAGMJGHF@Error?5in?5allocating?5memory@
	call	puts
; Line 36
	mov	ecx, 1
	call	exit
$LN2@Date:
; Line 39
	mov	rax, QWORD PTR L$[rsp]
	mov	rcx, QWORD PTR cc_strDate$[rsp]
	add	rcx, rax
	mov	rax, rcx
	mov	BYTE PTR [rax], 0
; Line 40
	mov	r8, QWORD PTR L$[rsp]
	mov	rdx, QWORD PTR strDate$[rsp]
	mov	rcx, QWORD PTR cc_strDate$[rsp]
	call	strncpy
; Line 42
	lea	rdx, OFFSET FLAT:??_C@_01JOAMLHOP@?9@
	mov	rcx, QWORD PTR cc_strDate$[rsp]
	call	strtok
	mov	QWORD PTR str_day$[rsp], rax
; Line 43
	lea	rdx, OFFSET FLAT:??_C@_01JOAMLHOP@?9@
	xor	ecx, ecx
	call	strtok
	mov	QWORD PTR str_month$[rsp], rax
; Line 44
	lea	rdx, OFFSET FLAT:??_C@_01JOAMLHOP@?9@
	xor	ecx, ecx
	call	strtok
	mov	QWORD PTR str_year$[rsp], rax
; Line 46
	mov	rcx, QWORD PTR str_day$[rsp]
	call	atoi
	mov	rcx, QWORD PTR this$[rsp]
	mov	DWORD PTR [rcx], eax
; Line 47
	mov	rcx, QWORD PTR str_month$[rsp]
	call	atoi
	mov	rcx, QWORD PTR this$[rsp]
	mov	DWORD PTR [rcx+4], eax
; Line 48
	mov	rcx, QWORD PTR str_year$[rsp]
	call	atoi
	mov	rcx, QWORD PTR this$[rsp]
	mov	DWORD PTR [rcx+8], eax
; Line 50
	mov	rcx, QWORD PTR cc_strDate$[rsp]
	call	free
; Line 51
	mov	QWORD PTR cc_strDate$[rsp], 0
; Line 52
	mov	rax, QWORD PTR this$[rsp]
$LN3@Date:
	add	rsp, 88					; 00000058H
	ret	0
??0Date@@QEAA@PEAD@Z ENDP				; Date::Date
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ?is_valid@Date@@AEAA_NHHH@Z
_TEXT	SEGMENT
this$ = 8
dd$ = 16
mm$ = 24
yy$ = 32
?is_valid@Date@@AEAA_NHHH@Z PROC			; Date::is_valid, COMDAT
; File C:\CPA_CPP\CLASS\This_Pointer\self.cpp
; Line 11
	mov	DWORD PTR [rsp+32], r9d
	mov	DWORD PTR [rsp+24], r8d
	mov	DWORD PTR [rsp+16], edx
	mov	QWORD PTR [rsp+8], rcx
; Line 12
	cmp	DWORD PTR dd$[rsp], 0
	jle	SHORT $LN3@is_valid
	cmp	DWORD PTR dd$[rsp], 31
	jle	SHORT $LN2@is_valid
$LN3@is_valid:
; Line 14
	xor	al, al
	jmp	SHORT $LN1@is_valid
$LN2@is_valid:
; Line 16
	cmp	DWORD PTR mm$[rsp], 0
	jle	SHORT $LN5@is_valid
	cmp	DWORD PTR mm$[rsp], 12
	jle	SHORT $LN4@is_valid
$LN5@is_valid:
; Line 18
	xor	al, al
	jmp	SHORT $LN1@is_valid
$LN4@is_valid:
; Line 20
	cmp	DWORD PTR yy$[rsp], 0
	jg	SHORT $LN6@is_valid
; Line 22
	xor	al, al
	jmp	SHORT $LN1@is_valid
$LN6@is_valid:
; Line 25
	mov	al, 1
$LN1@is_valid:
; Line 26
	ret	0
?is_valid@Date@@AEAA_NHHH@Z ENDP			; Date::is_valid
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT printf
_TEXT	SEGMENT
_Result$ = 32
_ArgList$ = 40
_Format$ = 64
printf	PROC						; COMDAT
; File C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt\stdio.h
; Line 956
$LN3:
	mov	QWORD PTR [rsp+8], rcx
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+24], r8
	mov	QWORD PTR [rsp+32], r9
	sub	rsp, 56					; 00000038H
; Line 959
	lea	rax, QWORD PTR _Format$[rsp+8]
	mov	QWORD PTR _ArgList$[rsp], rax
; Line 960
	mov	ecx, 1
	call	__acrt_iob_func
	mov	r9, QWORD PTR _ArgList$[rsp]
	xor	r8d, r8d
	mov	rdx, QWORD PTR _Format$[rsp]
	mov	rcx, rax
	call	_vfprintf_l
	mov	DWORD PTR _Result$[rsp], eax
; Line 961
	mov	QWORD PTR _ArgList$[rsp], 0
; Line 962
	mov	eax, DWORD PTR _Result$[rsp]
; Line 963
	add	rsp, 56					; 00000038H
	ret	0
printf	ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT _vfprintf_l
_TEXT	SEGMENT
_Stream$ = 64
_Format$ = 72
_Locale$ = 80
_ArgList$ = 88
_vfprintf_l PROC					; COMDAT
; File C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt\stdio.h
; Line 644
$LN3:
	mov	QWORD PTR [rsp+32], r9
	mov	QWORD PTR [rsp+24], r8
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 56					; 00000038H
; Line 645
	call	__local_stdio_printf_options
	mov	rcx, QWORD PTR _ArgList$[rsp]
	mov	QWORD PTR [rsp+32], rcx
	mov	r9, QWORD PTR _Locale$[rsp]
	mov	r8, QWORD PTR _Format$[rsp]
	mov	rdx, QWORD PTR _Stream$[rsp]
	mov	rcx, QWORD PTR [rax]
	call	__stdio_common_vfprintf
; Line 646
	add	rsp, 56					; 00000038H
	ret	0
_vfprintf_l ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT __local_stdio_printf_options
_TEXT	SEGMENT
__local_stdio_printf_options PROC			; COMDAT
; File C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt\corecrt_stdio_config.h
; Line 92
	lea	rax, OFFSET FLAT:?_OptionsStorage@?1??__local_stdio_printf_options@@9@4_KA ; `__local_stdio_printf_options'::`2'::_OptionsStorage
; Line 93
	ret	0
__local_stdio_printf_options ENDP
_TEXT	ENDS
END
