; Listing generated by Microsoft (R) Optimizing Compiler Version 19.24.28315.0 

include listing.inc

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

CONST	SEGMENT
$SG7251	DB	'28-2-2015', 00H
	ORG $+6
$SG7258	DB	'Initialization using three integer values', 00H
	ORG $+6
$SG7263	DB	'Initialization using string', 00H
CONST	ENDS
PUBLIC	?init_date@@YAXPEAUDate@@HHH@Z			; init_date
PUBLIC	?init_date@@YAXPEAUDate@@PEBD@Z			; init_date
PUBLIC	main
EXTRN	puts:PROC
EXTRN	__GSHandlerCheck:PROC
EXTRN	__security_check_cookie:PROC
EXTRN	__security_cookie:QWORD
pdata	SEGMENT
$pdata$?init_date@@YAXPEAUDate@@HHH@Z DD imagerel $LN3
	DD	imagerel $LN3+40
	DD	imagerel $unwind$?init_date@@YAXPEAUDate@@HHH@Z
$pdata$?init_date@@YAXPEAUDate@@PEBD@Z DD imagerel $LN3
	DD	imagerel $LN3+31
	DD	imagerel $unwind$?init_date@@YAXPEAUDate@@PEBD@Z
$pdata$main DD	imagerel $LN3
	DD	imagerel $LN3+83
	DD	imagerel $unwind$main
pdata	ENDS
xdata	SEGMENT
$unwind$?init_date@@YAXPEAUDate@@HHH@Z DD 011701H
	DD	04217H
$unwind$?init_date@@YAXPEAUDate@@PEBD@Z DD 010e01H
	DD	0420eH
$unwind$main DD	011319H
	DD	08204H
	DD	imagerel __GSHandlerCheck
	DD	030H
xdata	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
cpaDate$ = 32
__$ArrayPad$ = 48
main	PROC
; File C:\Users\yoges\OneDrive\Documents\CPA\CPP\BATCH_22\SESSION_04\function_overloading.cpp
; Line 13
$LN3:
	sub	rsp, 72					; 00000048H
	mov	rax, QWORD PTR __security_cookie
	xor	rax, rsp
	mov	QWORD PTR __$ArrayPad$[rsp], rax
; Line 16
	mov	r9d, 2015				; 000007dfH
	mov	r8d, 2
	mov	edx, 28
	lea	rcx, QWORD PTR cpaDate$[rsp]
	call	?init_date@@YAXPEAUDate@@HHH@Z		; init_date
; Line 17
	lea	rdx, OFFSET FLAT:$SG7251
	lea	rcx, QWORD PTR cpaDate$[rsp]
	call	?init_date@@YAXPEAUDate@@PEBD@Z		; init_date
; Line 19
	xor	eax, eax
; Line 20
	mov	rcx, QWORD PTR __$ArrayPad$[rsp]
	xor	rcx, rsp
	call	__security_check_cookie
	add	rsp, 72					; 00000048H
	ret	0
main	ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
pDate$ = 48
str_date$ = 56

?init_date@@YAXPEAUDate@@PEBD@Z PROC			; init_date

; File C:\Users\yoges\OneDrive\Documents\CPA\CPP\BATCH_22\SESSION_04\function_overloading.cpp
; Line 26
$LN3:
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 40					; 00000028H
; Line 27
	lea	rcx, OFFSET FLAT:$SG7263
	call	puts
; Line 28
	add	rsp, 40					; 00000028H
	ret	0
?init_date@@YAXPEAUDate@@PEBD@Z ENDP			; init_date
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
pDate$ = 48
day$ = 56
month$ = 64
year$ = 72

?init_date@@YAXPEAUDate@@HHH@Z PROC			; init_date

; File C:\Users\yoges\OneDrive\Documents\CPA\CPP\BATCH_22\SESSION_04\function_overloading.cpp
; Line 22
$LN3:
	mov	DWORD PTR [rsp+32], r9d
	mov	DWORD PTR [rsp+24], r8d
	mov	DWORD PTR [rsp+16], edx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 40					; 00000028H
; Line 23
	lea	rcx, OFFSET FLAT:$SG7258
	call	puts
; Line 24
	add	rsp, 40					; 00000028H
	ret	0
?init_date@@YAXPEAUDate@@HHH@Z ENDP			; init_date
_TEXT	ENDS
END
